# supported task types are 'classification', 'object_detection' and 'semantic_segmentation'.
# support 'learning rate' tuning at trainer.
task_type: {{ task_type }}

network_name: {{ network_name }}

dataset:
  format: {{ dataset_format }}
  train_path: {{ train_path }}
  test_path: {{ test_path }}

trainer:
  batch_size: {{ batch_size }}
  epochs: {{ training_epochs }}
  training_learning_rate: {{ training_learning_rate_setting }}
  initial_learning_rate: {{ initial_learning_rate_value }}  

common:
  image_size:
    - {{ image_size[0] }}  # height
    - {{ image_size[1] }}  # width

  # set pretrain model name. currently, this feature is not supported, always ignored.
  pretrain_model: false

  # enable dataset prefetch, set false if weired problem happens
  dataset_prefetch: true
