# supported task types are 'classification', 'object_detection' and 'semantic_segmentation'.
task_type: {{ task_type }}

network_name: {{ network_name }}

dataset:
  format: {{ dataset_format }}
  train_path: {{ train_path }}
  test_path: {{ test_path }}

trainer:
  batch_size: {{ batch_size }}
  epochs: {{ training_epochs }}

common:
  image_size:
    - {{ image_size[0] }}  # height
    - {{ image_size[1] }}  # width

  # set pretrain model name. currently, this feature is not supported, always ignored.
  pretrain_model: false

  # enable dataset prefetch, set false if weired problem happens
  dataset_prefetch: true
{% if data_augmentation %}
  data_augmentation:
{%- for name, defaults in data_augmentation.items() %}
    - {{ name }}:
      {% for d_name, d_value in defaults -%}
        - {{ d_name }}: {{ d_value }}
{%- endfor -%}
{% endfor %}
{% endif %}